{% set version = "3.0.0" %}

package:
  name: github3.py
  version: {{ version }}

source:
  fn: github3.py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/github3.py/github3.py-{{ version }}.tar.gz
  sha256: a9134cb9efd334b1644ad7c5ee3ff3ff488317c4549ffc0e8d82e4d63383a1a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - requests >=2.18
    - uritemplate >=3.0.0
    - python-dateutil >=2.6.0
    - jwcrypto

test:
  imports:
    - github3
    - github3.gists
    - github3.issues
    - github3.repos
    - github3.search
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github3py.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python wrapper for the GitHub API (http://developer.github.com/v3).

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - sigmavirus24
    - scopatz
