{% set version = "1.3.0" %}

package:
  name: github3.py
  version: {{ version }}

source:
  fn: github3.py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/github3.py/github3.py-{{ version }}.tar.gz
  sha256: 15a115c18f7bfcf934dfef7ab103844eb9f620c586bad65967708926da47cbda

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - requests >=2.18
    - uritemplate.py >=3.0.0
    - python-dateutil >=2.6.0
    - jwcrypto

test:
  imports:
    - github3
    - github3.gists
    - github3.issues
    - github3.repos
    - github3.search

about:
  home: https://github3py.readthedocs.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python wrapper for the GitHub API (http://developer.github.com/v3).'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - sigmavirus24
    - scopatz
