{% set version = "2.0.0" %}

package:
  name: github3.py
  version: {{ version }}

source:
  fn: github3.py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/github3.py/github3.py-{{ version }}.tar.gz
  sha256: 8dd4ac612fd60cb277eaf6e2ce02f68dda54aba06870ca6fa2b28369bf39aa14

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
    - requests >=2.18
    - uritemplate.py >=3.0.0
    - python-dateutil >=2.6.0
    - jwcrypto

test:
  imports:
    - github3
    - github3.gists
    - github3.issues
    - github3.repos
    - github3.search

about:
  home: https://github3py.readthedocs.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Python wrapper for the GitHub API (http://developer.github.com/v3).

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - sigmavirus24
    - scopatz
