# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZZ0CeDZER6S9h6/dXEbQTwRQCmhnRISEK21Bg5jyOl2Wn5Sj3+tH03Qg9pU/6TAXsSQx7RLboDz0UExA+37Cqd2o3ZZseTDum6XPzO0MPFyaZi364YF0E6ERhdfb18KJQvFQDJ1mVWKN0sKZ1ESsRf8T5fqYY051X1MUpjIX7Mp8nexg5e/76xbfgM8lt6vHqynXGFz0SC2u1e7DHOcMhn/39VgMas8VUMmZEXm432Ml55Ia54t4OUAYH/PiVOUGfoppuwVU/SbRmk0b4Q5cF7cGgURYxPGgFvprRYNdaR1Lyw/s5uBgIhnp5jyN31e0HiQq8ER6UKiUxzm8IaMJ+WQLDW447pL6nsbUEJX2s5A19KN9cOaysDeGwiUl9Z1D4Oi/DaLFZWh5HzxhOOvz++deSV2bSV7ZypwNMpJRJcDys4317WZgVD6yN1otuxxnxhMjsdZzEOmaxltnCEfL+okcNKVp+wIbSoUG6YWcTI16Xcq85beXGJqakaHTFKUW1ihCYjPq9k7KRuQcx6J+5kxDz2yInhQbVtJTvq5FAcMZ/1P+K6Zg2IiBc8iVOhfkav3wN71I1ln92ki/41/Et49bGn8ahxNCNNzmD6hpxEMR0hxKYoHx4/8RjBpPL0u6MFjkMGkbBasTE9sDkxybO9pHv1XA1/x4/iV+Az0Ou8c="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
