travis:
  secure:
    BINSTAR_TOKEN: QKyVrBSj+axUjI7R1E7CWguIPe7CiKSMBJ0lPGGTgzJElxdyln4ISNAJzdb3wFkRmVQj5qxM8Gr3HMosicQACv9XNPkG17hCId2qklOBCxsHunTZKDgAdq/vdyNI4fo8pebygkp6GZ/d/U85z9vaAAU5+zsoo98TQdM5ihY3L4+opkWoPJeufQdYJKqk7GWrtuSuGFgWIjZGKJuDBkLVY3851hxh6huR9KMKoycbhGJ4aPmymBrah1Dbfu+aIxvWVGz+fhMv/+h6rrbXWGzLkzDyxXUjJtP5s165TJK0pfh0noldNRmf44Brxq//oTWHuaCWo0yCQlXkZRY7TDKH6BqUbRGh0rGf9KEBcjYRBz2OhOOa9MrP0GGUu4Hz3t2H2ITG0C4YyFCtNGxX5NvcL/aRZ3GCD3tuLsU3l5MDaDj6rrZaEEKt2YUPDnGBmiQcMzENmJ1CnOem57oSL4rZXjBZYukCrDa/Bu7YSJivHbzax1TLN5KtZYw+hpurlFbOv2RjP+X+VAKYwXhJhUkvhdxZf8G467Q0NGwqTPatfD4BNFBTmtwZYVqxJxZ/JfzP/DZmoaXtwVHNO/fOZqZL6v8AvPyD1ZP72YpWJDNJlQ8+jZpLc4gFdTZgOAgC4kfu2herW2KVZbnEOUTEw5oTtrD2rU4ul5ltWI4pQxs+Dpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
