travis:
  secure:
    BINSTAR_TOKEN: gD91LUoplI6mvPZXGz/zR8APA8yHMNkhPT3BOGmwYW7G4Iq98BDhLBTHzKacsElOTNLUkpXQZTaFJzTVCqmc2pGsFcEOWdion8kqTVjsv93/PpVtDJqnhkENWbNU8KuLwrpxhy7D7lk+NYLE3FHGfTrZDB6A9J2oldiH5GLV2hif2Olgljg2i35/bV5wIxnLKErZtiaAy0BnUnGB7P1UvRvzSlL3Nyur8BOxX2wVub4iJuFFozTAt1K5eOy2DN0Br63yw8RVnBBJf5DJOzJuvIPKMptv4q0Uv0E+7kxk0pZ4eX7HJWnvASAu6qlN1wso62A6CQJ7X2eCeNpGwZOlE853F7io/vCnbxS2sdFpP+YUgbPJpDvCsjEnrV4M485OcNxHmjikyK/lDR7s9njdE25DJYMNqcIq4RUYnTCpNlRIUq3ZzQ3MNeAC25sAkzrMdmnKXh8lxjy34Wr+iWaBCFEFV/m9aewsRKbwBiKx4tZsJrMDc0YlRE8zPAOf8nTCdbFhl0UANxOvCJttinThIIbHtj45eOng36QewMnYDRTuYEXHWLeT37yqhRS6E4wOhNSczU5srzU+utvXSVm0pAdbxs4dTPPDuP5UrCyaBoGZgtTOqBx34qQrDNk28WvHL9Ym4jNGO3vm7lmSG4avZgSQsA8QE8esx1W1JdvYmr4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
