travis:
  secure:
    BINSTAR_TOKEN: AvrzEuQzF/+I2Lhx1z6CZF4szbRQ4V5uLNKm/lveAjm5xnqwj82CKbbDy43tQmHD8xbtaD6ieSatQpTYNfi5h6Jq+fmDQqLtQ4R5iHSAS4xWxUDdJ+O0ut+CatP6pVKX20VtVMOCE8T1H0xxskrEL+xHv8smr51ONbThpYqhFMPJcQkfNOcPTaa4F52Df6pl16e7EZ8fTSPssLr3RDoJBhkCEwPohbv0U6zgVMPsF7hDYWaDO5ylOEdAiXGERw09N4i6tTe3+4VkL648pUUrm7vxP/e+G3HNMTm00MNeqmPbn9ieyALqsn1Am/wxRQA0diVOVseV+kUAcNhNPbU8k553gar2+0wc07yLyKrfE8XN/LSPC7sczjXp+skDC4e3DttY1JbXzuEJjTUhaIGoC7TkqrMSb8WNccsmx+4+fblfjInHIcVo8auxivMFKGTVgxw9gUR73n3hzKu5oqGXE+II+2onfhneJE19/91tiMeDjSNHxumSxzCF9aqScmlsi/VF/z7I1Rh8hV3YuICwqEf+XgFBshJg6/JvhQ8ErpoNbjbiWRgFZDLnX0ljcmuZxNUuVNtjNCcD5hQJJk8ievjIJer99Xw52LIkQ9RZTrkeIJ4kbp1q6Im/Em6dYsA4LWiPtIUCU1kDRSG2Rlp57la9hpXHliafTht0XncF36U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
