travis:
  secure:
    BINSTAR_TOKEN: EqImFYj52oIQUs/Auz1C2UlhUEDS4BWAJNPbFpP8WEgnTKV7c83CzvQGdAI0VBepaMcsz3NB8QMFS69dL3T/p3HRX3gU/ejo8PBe11wNrEd/8iw1eUeG+2CE6360PuaytOpb/mG3HsgHmfp2jB2N4+CkVJXfA+XbJeggDRP+4RHrgOfWQkJN4nSAoDTyb6QU36wQr9WID+fPEASqQSXLn1PqUhGoocPcZ2VnYHeIEVixK/3Ev18lxRRWvfpzJQJ3dqwH9pNecsDxm/bAi+hzoT/GP8d1uukpxzDMDZc18ZClEnwnlrHnAohv7kiXVigrDszAnIoI+KCaEX3LNQM69XN8UPgqShnYAYHu8lgRmzfYLNJLiO8akVaDf6YzHKSWV+4xvYtDyu7WYHuDF9Kigswxqk/57nXxrWoSL/96nrSbZxSQSoNHAll653rFtEBzFh/ftoRt07W1tEetoKlNZ6NSRCjNktbgVMpKCr00lp9UiwtbkPcTQm3jj342Ghw8afywiXrgFeTcZiQBajqYmIwu1AtdPLTzB35yzlowR4Hjs4IA14t9k2SseU2leHAb+zY+XHx9p/phAxywi4jl3Ss8DBmCRIO246TFyhjn62HSTPkAYgD6VwGJcor17Ud0k/594UetohLrIuiel+5y1ZaVV20Xikykll/mJMrlfaE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
